project_root: .
model_name: PLEASE FILL
device: cuda

global_training:
  training_objective: causal
  context_length: 48
  inference_batch_size: 10
  batch_size: 10
  learning_rate: 0.0001
  optimizer: {name: AdamW}
  scheduler: {name: StepLR, step_size: 1, gamma: 0.99}
  scheduler_step_on: epoch
  reset_optimization_on_phase: true

model:
  backbone:
    architecture:
      dim_model: 128
      max_context_length: 512
      num_layers: 3
      attention: {n_heads: 16}
      feed_forward: {dim: 128}
      dropout: 0.2
  interface:
    input_columns: [EXAMPLE_INPUT_COLUMN_NAME]
    target_columns: [EXAMPLE_TARGET_COLUMN_NAME]
    ingestion: {type: embedding, output_dim: 128}
    decoder: {type: linear, prediction_length: 1}

dataset:
  part: {metadata_config_path: PLEASE FILL}
  criterion: {EXAMPLE_TARGET_COLUMN_NAME: MSELoss}

training_plan: {epochs: 10}

evaluation: true

export_generative_model: PLEASE FILL # true or false
export_embedding_model: PLEASE FILL # true or false
